// @bazza-ui/data-views — Recursive Filter Tree
// Pure filter tree state helpers and transition functions.

import { addUniq, removeUniq, uniq } from '../lib/array.js'
import {
  createBigIntFilterValue,
  createDateFilterValue,
  createNumberFilterValue,
} from '../lib/helpers.js'
import type { OperatorSet } from './operator-set.js'
import { determineNewOperator, getOperatorSet } from './operators.js'
import type { ColumnDataType } from './types.js'

export type FilterCondition = {
  kind: 'condition'
  /** Stable node id. */
  id: string
  /** Column id this condition filters. */
  columnId: string
  /** Column data type, stored for server-side interpretation. */
  type: ColumnDataType
  operator: string
  values: unknown[]
}

export type FilterGroup = {
  kind: 'group'
  id: string
  op: 'and' | 'or'
  children: FilterNode[]
}

export type FilterNode = FilterCondition | FilterGroup

/** Root is ALWAYS a group. */
export type FiltersState = FilterGroup

let nodeIdCounter = 0

/**
 * Creates a dependency-free, collision-tolerant stable node id.
 *
 * The id combines wall-clock time, a process-local counter, and random entropy.
 * Callers own persistence; existing nodes are never regenerated by operations.
 */
export function createNodeId(): string {
  nodeIdCounter = (nodeIdCounter + 1) % Number.MAX_SAFE_INTEGER

  return [
    'filter',
    Date.now().toString(36),
    nodeIdCounter.toString(36),
    Math.random().toString(36).slice(2, 10),
  ].join('_')
}

export function createEmptyFilters(): FiltersState {
  return {
    kind: 'group',
    id: createNodeId(),
    op: 'and',
    children: [],
  }
}

export function isCondition(n: FilterNode): n is FilterCondition {
  return n.kind === 'condition'
}

export function isGroup(n: FilterNode): n is FilterGroup {
  return n.kind === 'group'
}

export function findNode(
  state: FiltersState,
  nodeId: string,
): FilterNode | undefined {
  if (state.id === nodeId) return state

  const stack = [...state.children]
  while (stack.length > 0) {
    const node = stack.shift()!
    if (node.id === nodeId) return node
    if (isGroup(node)) stack.unshift(...node.children)
  }

  return undefined
}

export function findConditionsForColumn(
  state: FiltersState,
  columnId: string,
): FilterCondition[] {
  const conditions: FilterCondition[] = []

  function visit(node: FilterNode) {
    if (isCondition(node)) {
      if (node.columnId === columnId) conditions.push(node)
      return
    }

    for (const child of node.children) visit(child)
  }

  visit(state)
  return conditions
}

export function countConditions(state: FiltersState): number {
  let count = 0

  function visit(node: FilterNode) {
    if (isCondition(node)) {
      count += 1
      return
    }

    for (const child of node.children) visit(child)
  }

  visit(state)
  return count
}

function normalizeNode(
  node: FilterNode,
  isRootNode: boolean,
): FilterNode | undefined {
  if (isCondition(node)) {
    return node.values.length === 0 ? undefined : node
  }

  let changed = false
  const children: FilterNode[] = []

  for (const child of node.children) {
    const normalizedChild = normalizeNode(child, false)

    if (!normalizedChild) {
      changed = true
      continue
    }

    if (normalizedChild !== child) changed = true
    children.push(normalizedChild)
  }

  if (!isRootNode) {
    if (children.length === 0) return undefined

    const onlyChild = children[0]
    if (children.length === 1 && onlyChild && isGroup(onlyChild)) {
      return onlyChild
    }

    if (changed || children.length !== node.children.length) {
      return { ...node, children }
    }

    return node
  }

  const onlyChild = children[0]
  if (children.length === 1 && onlyChild && isGroup(onlyChild)) {
    return { ...onlyChild, id: node.id }
  }

  if (changed || children.length !== node.children.length) {
    return { ...node, children }
  }

  return node
}

/**
 * Applies filter tree normalization invariants:
 * - empty non-root groups are removed
 * - groups with exactly one group child are collapsed
 * - empty-value conditions are removed
 * - root is always preserved with its original id
 */
export function normalizeFilters(state: FiltersState): FiltersState {
  const normalized = normalizeNode(state, true)

  if (!normalized || !isGroup(normalized)) {
    return { ...state, children: [] }
  }

  return normalized
}

const groupNotFoundError = (id: string) =>
  new Error(`[data-views] Group "${id}" not found`)

function addNodeToGroup(
  group: FilterGroup,
  parentGroupId: string,
  node: FilterNode,
): { group: FilterGroup; found: boolean; foundNonGroup: boolean } {
  if (group.id === parentGroupId) {
    return {
      group: { ...group, children: [...group.children, node] },
      found: true,
      foundNonGroup: false,
    }
  }

  let found = false
  let foundNonGroup = false
  let changed = false

  const children = group.children.map((child) => {
    if (child.id === parentGroupId && isCondition(child)) {
      found = true
      foundNonGroup = true
      return child
    }

    if (!isGroup(child)) return child

    const result = addNodeToGroup(child, parentGroupId, node)
    if (result.found) found = true
    if (result.foundNonGroup) foundNonGroup = true
    if (result.group !== child) changed = true
    return result.group
  })

  return {
    group: changed ? { ...group, children } : group,
    found,
    foundNonGroup,
  }
}

function removeNodeFromGroup(
  group: FilterGroup,
  nodeId: string,
): { group: FilterGroup; removed: boolean } {
  let removed = false
  let changed = false
  const children: FilterNode[] = []

  for (const child of group.children) {
    if (child.id === nodeId) {
      removed = true
      changed = true
      continue
    }

    if (isGroup(child)) {
      const result = removeNodeFromGroup(child, nodeId)
      if (result.removed) removed = true
      if (result.group !== child) changed = true
      children.push(result.group)
      continue
    }

    children.push(child)
  }

  return {
    group: changed ? { ...group, children } : group,
    removed,
  }
}

function updateConditionInGroup(
  group: FilterGroup,
  nodeId: string,
  patch: Partial<Pick<FilterCondition, 'operator' | 'values'>>,
): { group: FilterGroup; changed: boolean } {
  let changed = false

  const children = group.children.map((child) => {
    if (isCondition(child)) {
      if (child.id !== nodeId) return child

      const next: FilterCondition = {
        ...child,
        operator: patch.operator ?? child.operator,
        values: patch.values ?? child.values,
      }

      if (next.operator === child.operator && next.values === child.values) {
        return child
      }

      changed = true
      return next
    }

    const result = updateConditionInGroup(child, nodeId, patch)
    if (result.group !== child) changed = true
    return result.group
  })

  return {
    group: changed ? { ...group, children } : group,
    changed,
  }
}

function setGroupOperatorInGroup(
  group: FilterGroup,
  nodeId: string,
  op: FilterGroup['op'],
): { group: FilterGroup; changed: boolean } {
  if (group.id === nodeId) {
    return {
      group: group.op === op ? group : { ...group, op },
      changed: group.op !== op,
    }
  }

  let changed = false

  const children = group.children.map((child) => {
    if (!isGroup(child)) return child

    const result = setGroupOperatorInGroup(child, nodeId, op)
    if (result.group !== child) changed = true
    return result.group
  })

  return {
    group: changed ? { ...group, children } : group,
    changed,
  }
}

function findParentGroup(
  group: FilterGroup,
  nodeId: string,
): FilterGroup | undefined {
  for (const child of group.children) {
    if (child.id === nodeId) return group
    if (isGroup(child)) {
      const parent = findParentGroup(child, nodeId)
      if (parent) return parent
    }
  }

  return undefined
}

function replaceGroupChildren(
  group: FilterGroup,
  groupId: string,
  replace: (children: FilterNode[]) => FilterNode[],
): FilterGroup {
  if (group.id === groupId) {
    const children = replace(group.children)
    return children === group.children ? group : { ...group, children }
  }

  let changed = false
  const children = group.children.map((child) => {
    if (!isGroup(child)) return child

    const next = replaceGroupChildren(child, groupId, replace)
    if (next !== child) changed = true
    return next
  })

  return changed ? { ...group, children } : group
}

const sharedParentError = () =>
  new Error(
    '[data-views] groupNodes() requires nodes to share the same parent group',
  )

export const filterTreeOperations = {
  addNode(
    state: FiltersState,
    parentGroupId: string,
    node: FilterNode,
  ): FiltersState {
    const result = addNodeToGroup(state, parentGroupId, node)

    if (!result.found || result.foundNonGroup) {
      throw groupNotFoundError(parentGroupId)
    }

    return normalizeFilters(result.group)
  },

  removeNode(state: FiltersState, nodeId: string): FiltersState {
    if (state.id === nodeId) return normalizeFilters(state)

    const result = removeNodeFromGroup(state, nodeId)
    return normalizeFilters(result.group)
  },

  updateCondition(
    state: FiltersState,
    nodeId: string,
    patch: Partial<Pick<FilterCondition, 'operator' | 'values'>>,
  ): FiltersState {
    const result = updateConditionInGroup(state, nodeId, patch)
    return normalizeFilters(result.group)
  },

  setGroupOperator(
    state: FiltersState,
    nodeId: string,
    op: FilterGroup['op'],
  ): FiltersState {
    const result = setGroupOperatorInGroup(state, nodeId, op)
    return normalizeFilters(result.group)
  },

  groupNodes(
    state: FiltersState,
    nodeIds: string[],
    op: FilterGroup['op'],
  ): FiltersState {
    const uniqueNodeIds = [...new Set(nodeIds)]
    if (uniqueNodeIds.length === 0) return normalizeFilters(state)

    const parent = findParentGroup(state, uniqueNodeIds[0]!)
    if (!parent) throw sharedParentError()

    for (const nodeId of uniqueNodeIds.slice(1)) {
      const currentParent = findParentGroup(state, nodeId)
      if (!currentParent || currentParent.id !== parent.id) {
        throw sharedParentError()
      }
    }

    const selectedIds = new Set(uniqueNodeIds)
    const selectedChildren = parent.children.filter((child) =>
      selectedIds.has(child.id),
    )

    if (selectedChildren.length !== uniqueNodeIds.length) {
      throw sharedParentError()
    }

    const group: FilterGroup = {
      kind: 'group',
      id: createNodeId(),
      op,
      children: selectedChildren,
    }

    const next = replaceGroupChildren(state, parent.id, (children) => {
      const nextChildren: FilterNode[] = []
      let inserted = false

      for (const child of children) {
        if (selectedIds.has(child.id)) {
          if (!inserted) {
            nextChildren.push(group)
            inserted = true
          }
          continue
        }

        nextChildren.push(child)
      }

      return nextChildren
    })

    return normalizeFilters(next)
  },

  ungroupNode(state: FiltersState, groupId: string): FiltersState {
    if (state.id === groupId) {
      throw new Error('[data-views] Cannot ungroup the root group')
    }

    const parent = findParentGroup(state, groupId)
    if (!parent) return normalizeFilters(state)

    const target = parent.children.find((child) => child.id === groupId)
    if (!target || !isGroup(target)) return normalizeFilters(state)

    const next = replaceGroupChildren(state, parent.id, (children) => {
      const nextChildren: FilterNode[] = []

      for (const child of children) {
        if (child.id === groupId && isGroup(child)) {
          nextChildren.push(...child.children)
          continue
        }

        nextChildren.push(child)
      }

      return nextChildren
    })

    return normalizeFilters(next)
  },
}

type FilterColumn = {
  id: string
  type: ColumnDataType
  operators?: OperatorSet
  columnType?: { operators: OperatorSet }
}

function findRootCondition(
  state: FiltersState,
  columnId: string,
): FilterCondition | undefined {
  return state.children.find(
    (child): child is FilterCondition =>
      isCondition(child) && child.columnId === columnId,
  )
}

function replaceRootCondition(
  state: FiltersState,
  nodeId: string,
  condition: FilterCondition,
): FiltersState {
  let changed = false

  const children = state.children.map((child) => {
    if (isCondition(child) && child.id === nodeId) {
      changed = true
      return condition
    }

    return child
  })

  return changed ? { ...state, children } : state
}

function removeRootCondition(
  state: FiltersState,
  nodeId: string,
): FiltersState {
  let changed = false
  const children: FilterNode[] = []

  for (const child of state.children) {
    if (isCondition(child) && child.id === nodeId) {
      changed = true
      continue
    }

    children.push(child)
  }

  return changed ? { ...state, children } : state
}

function normalizeFilterValues(
  column: FilterColumn,
  values: unknown[] | undefined,
): unknown[] {
  if (column.type === 'number') {
    return createNumberFilterValue(values as number[] | undefined)
  }

  if (column.type === 'bigint') {
    return createBigIntFilterValue(values as bigint[] | undefined)
  }

  if (column.type === 'date') {
    return createDateFilterValue(
      values as [Date, Date] | [Date] | [] | undefined,
    )
  }

  return uniq(values ?? [])
}

function removeColumnConditionsFromGroup(
  group: FilterGroup,
  columnId: string,
): { group: FilterGroup; changed: boolean } {
  let changed = false
  const children: FilterNode[] = []

  for (const child of group.children) {
    if (isCondition(child)) {
      if (child.columnId === columnId) {
        changed = true
        continue
      }

      children.push(child)
      continue
    }

    const result = removeColumnConditionsFromGroup(child, columnId)
    if (result.group !== child) changed = true
    children.push(result.group)
  }

  return {
    group: changed ? { ...group, children } : group,
    changed,
  }
}

function assertOptionColumn(column: FilterColumn, operation: string) {
  if (column.type !== 'option' && column.type !== 'multiOption') {
    throw new Error(
      `[data-views] ${operation}() is only supported for option and multiOption columns`,
    )
  }
}

function createCondition(
  column: FilterColumn,
  operator: string,
  values: unknown[],
): FilterCondition {
  return {
    kind: 'condition',
    id: createNodeId(),
    columnId: column.id,
    type: column.type,
    operator,
    values,
  }
}

/**
 * Flat-style filter conveniences over root-level conditions.
 * Nested groups are intentionally left untouched except for removeFilter(),
 * which removes a column's conditions tree-wide to match chip removal UX.
 */
export const filterOperations = {
  addFilterValue(
    state: FiltersState,
    column: FilterColumn,
    values: unknown[] | undefined,
  ): FiltersState {
    assertOptionColumn(column, 'addFilterValue')

    const nextValues = values ?? []
    const operatorSet = getOperatorSet(column)
    const filter = findRootCondition(state, column.id)
    const isColumnFiltered = Boolean(filter && filter.values.length > 0)

    if (!filter || !isColumnFiltered) {
      const target = nextValues.length > 1 ? 'multiple' : 'single'
      const condition = createCondition(
        column,
        operatorSet.getDefault(target).id,
        nextValues,
      )

      return normalizeFilters({
        ...state,
        children: [...state.children, condition],
      })
    }

    const oldValues = filter.values
    const newValues = addUniq(oldValues, nextValues)
    const newOperator = determineNewOperator(
      operatorSet,
      oldValues,
      newValues,
      filter.operator,
    )

    if (newValues.length === 0) {
      return normalizeFilters(removeRootCondition(state, filter.id))
    }

    return normalizeFilters(
      replaceRootCondition(state, filter.id, {
        ...filter,
        type: column.type,
        operator: newOperator,
        values: newValues,
      }),
    )
  },

  removeFilterValue(
    state: FiltersState,
    column: FilterColumn,
    values: unknown[] | undefined,
  ): FiltersState {
    assertOptionColumn(column, 'removeFilterValue')

    const nextValues = values ?? []
    const filter = findRootCondition(state, column.id)
    const isColumnFiltered = Boolean(filter && filter.values.length > 0)

    if (!filter || !isColumnFiltered) return normalizeFilters(state)

    const operatorSet = getOperatorSet(column)
    const oldValues = filter.values
    const newValues = removeUniq(oldValues, nextValues)
    const newOperator = determineNewOperator(
      operatorSet,
      oldValues,
      newValues,
      filter.operator,
    )

    if (newValues.length === 0) {
      return normalizeFilters(removeRootCondition(state, filter.id))
    }

    return normalizeFilters(
      replaceRootCondition(state, filter.id, {
        ...filter,
        type: column.type,
        operator: newOperator,
        values: newValues,
      }),
    )
  },

  setFilterValue(
    state: FiltersState,
    column: FilterColumn,
    values: unknown[] | undefined,
  ): FiltersState {
    const operatorSet = getOperatorSet(column)
    const filter = findRootCondition(state, column.id)
    const isColumnFiltered = Boolean(filter && filter.values.length > 0)
    const newValues = normalizeFilterValues(column, values)

    if (newValues.length === 0) return normalizeFilters(state)

    if (!filter || !isColumnFiltered) {
      const target = newValues.length > 1 ? 'multiple' : 'single'
      const condition = createCondition(
        column,
        operatorSet.getDefault(target).id,
        newValues,
      )

      return normalizeFilters({
        ...state,
        children: [...state.children, condition],
      })
    }

    const oldValues = filter.values
    const newOperator = determineNewOperator(
      operatorSet,
      oldValues,
      newValues,
      filter.operator,
    )

    return normalizeFilters(
      replaceRootCondition(state, filter.id, {
        ...filter,
        type: column.type,
        operator: newOperator,
        values: newValues,
      }),
    )
  },

  setFilterOperator(
    state: FiltersState,
    columnId: string,
    operator: string,
  ): FiltersState {
    let changed = false

    const children = state.children.map((child) => {
      if (isCondition(child) && child.columnId === columnId) {
        if (child.operator === operator) return child
        changed = true
        return { ...child, operator }
      }

      return child
    })

    return normalizeFilters(changed ? { ...state, children } : state)
  },

  removeFilter(state: FiltersState, columnId: string): FiltersState {
    const result = removeColumnConditionsFromGroup(state, columnId)
    return normalizeFilters(result.group)
  },

  removeAllFilters(state: FiltersState): FiltersState {
    return {
      kind: 'group',
      id: state.id,
      op: 'and',
      children: [],
    }
  },
}
