// CRA RC4088 Appendix A, General Index of Financial Information (GIFI), Rev. 23.
// Sourced from the Canada.ca HTML guide and kept static.

export const GIFI_STATEMENT_LABELS = {
  assets: 'Assets',
  liabilities: 'Liabilities',
  equity: 'Equity',
  revenue: 'Revenue',
  expenses: 'Expenses',
  farming: 'Farming',
  extraordinary_and_taxes: 'Extraordinary and taxes',
} as const

export type GifiStatement = keyof typeof GIFI_STATEMENT_LABELS

export interface GifiItem {
  code: string
  name: string
  statement: GifiStatement
}

export const GIFI_CATALOG: GifiItem[] = [
  { code: '1000', name: 'Cash and deposits', statement: 'assets' },
  { code: '1001', name: 'Cash', statement: 'assets' },
  {
    code: '1002',
    name: 'Deposits in Canadian banks and institutions - Canadian currency',
    statement: 'assets',
  },
  {
    code: '1003',
    name: 'Deposits in Canadian banks and institutions - Foreign currency',
    statement: 'assets',
  },
  {
    code: '1004',
    name: 'Deposits in foreign banks - Canadian currency',
    statement: 'assets',
  },
  {
    code: '1005',
    name: 'Deposits in foreign banks - Foreign currency',
    statement: 'assets',
  },
  { code: '1006', name: 'Credit union central deposits', statement: 'assets' },
  { code: '1007', name: 'Other cash-like instruments', statement: 'assets' },
  { code: '1060', name: 'Accounts receivable', statement: 'assets' },
  {
    code: '1061',
    name: 'Allowance for doubtful accounts',
    statement: 'assets',
  },
  { code: '1062', name: 'Trade accounts receivable', statement: 'assets' },
  {
    code: '1063',
    name: 'Allowance for doubtful trade accounts receivable',
    statement: 'assets',
  },
  {
    code: '1064',
    name: 'Trade accounts receivable from related parties',
    statement: 'assets',
  },
  {
    code: '1065',
    name: 'Allowance for doubtful trade accounts receivable from related parties',
    statement: 'assets',
  },
  { code: '1066', name: 'Taxes receivable', statement: 'assets' },
  { code: '1067', name: 'Interest receivable', statement: 'assets' },
  { code: '1068', name: 'Holdbacks receivable', statement: 'assets' },
  { code: '1069', name: 'Leases receivable', statement: 'assets' },
  {
    code: '1070',
    name: 'Allowance for doubtful amounts contained in leases receivable',
    statement: 'assets',
  },
  {
    code: '1071',
    name: 'Accounts receivable from employees',
    statement: 'assets',
  },
  {
    code: '1072',
    name: 'Allowance for doubtful accounts receivable from employees',
    statement: 'assets',
  },
  {
    code: '1073',
    name: 'Amounts receivable from members of NPOs',
    statement: 'assets',
  },
  { code: '1120', name: 'Inventories', statement: 'assets' },
  { code: '1121', name: 'Inventory of goods for sale', statement: 'assets' },
  { code: '1122', name: 'Inventory parts and supplies', statement: 'assets' },
  { code: '1123', name: 'Inventory properties', statement: 'assets' },
  { code: '1124', name: 'Inventory of aggregates', statement: 'assets' },
  { code: '1125', name: 'Work in progress', statement: 'assets' },
  { code: '1126', name: 'Raw materials', statement: 'assets' },
  { code: '1127', name: 'Inventory of securities', statement: 'assets' },
  { code: '1180', name: 'Short-term investments', statement: 'assets' },
  { code: '1181', name: 'Canadian term deposits', statement: 'assets' },
  { code: '1182', name: 'Canadian shares', statement: 'assets' },
  { code: '1183', name: 'Canadian bonds', statement: 'assets' },
  { code: '1184', name: 'Canadian treasury bills', statement: 'assets' },
  {
    code: '1185',
    name: 'Securities purchased under resale agreements',
    statement: 'assets',
  },
  {
    code: '1186',
    name: 'Other short-term Canadian investments',
    statement: 'assets',
  },
  { code: '1187', name: 'Short-term foreign investments', statement: 'assets' },
  { code: '1240', name: 'Loans and notes receivable', statement: 'assets' },
  { code: '1241', name: 'Demand loans receivable', statement: 'assets' },
  { code: '1242', name: 'Other loans receivable', statement: 'assets' },
  { code: '1243', name: 'Notes receivable', statement: 'assets' },
  { code: '1244', name: 'Mortgages receivable', statement: 'assets' },
  {
    code: '1300',
    name: 'Due from shareholder(s)/director(s)',
    statement: 'assets',
  },
  {
    code: '1301',
    name: 'Due from individual shareholder(s)',
    statement: 'assets',
  },
  {
    code: '1302',
    name: 'Due from corporate shareholder(s)',
    statement: 'assets',
  },
  { code: '1303', name: 'Due from director(s)', statement: 'assets' },
  {
    code: '1310',
    name: 'Due from member(s)/general partner(s)',
    statement: 'assets',
  },
  { code: '1311', name: 'Due from limited partners', statement: 'assets' },
  {
    code: '1312',
    name: 'Due from members that are partnerships',
    statement: 'assets',
  },
  { code: '1313', name: 'Due from general partners', statement: 'assets' },
  {
    code: '1314',
    name: 'Due from specified members who are not limited partners',
    statement: 'assets',
  },
  {
    code: '1360',
    name: 'Investment in joint venture(s)/partnership(s)',
    statement: 'assets',
  },
  {
    code: '1380',
    name: 'Due from joint venture(s)/partnership(s)',
    statement: 'assets',
  },
  {
    code: '1400',
    name: 'Due from/investment in related parties',
    statement: 'assets',
  },
  {
    code: '1401',
    name: 'Demand notes from related parties',
    statement: 'assets',
  },
  {
    code: '1402',
    name: 'Interest receivable from related parties',
    statement: 'assets',
  },
  {
    code: '1403',
    name: 'Loans/advances due from related parties',
    statement: 'assets',
  },
  {
    code: '1460',
    name: "Customers' liability under acceptances",
    statement: 'assets',
  },
  { code: '1480', name: 'Other current assets', statement: 'assets' },
  {
    code: '1481',
    name: 'Future (deferred) income taxes (corporations only)',
    statement: 'assets',
  },
  { code: '1482', name: 'Accrued investment income', statement: 'assets' },
  { code: '1483', name: 'Taxes recoverable/refundable', statement: 'assets' },
  { code: '1484', name: 'Prepaid expenses', statement: 'assets' },
  { code: '1485', name: 'Drilling advances', statement: 'assets' },
  { code: '1486', name: 'Security/tender deposits', statement: 'assets' },
  { code: '1599', name: 'Total current asset', statement: 'assets' },
  { code: '1600', name: 'Land', statement: 'assets' },
  { code: '1601', name: 'Land improvements', statement: 'assets' },
  {
    code: '1602',
    name: 'Accumulated amortization of land improvements',
    statement: 'assets',
  },
  { code: '1620', name: 'Depletable assets', statement: 'assets' },
  {
    code: '1621',
    name: 'Accumulated amortization of depletable assets',
    statement: 'assets',
  },
  {
    code: '1622',
    name: 'Petroleum and natural gas properties',
    statement: 'assets',
  },
  {
    code: '1623',
    name: 'Accumulated amortization of petroleum and natural gas properties',
    statement: 'assets',
  },
  { code: '1624', name: 'Mining properties', statement: 'assets' },
  {
    code: '1625',
    name: 'Accumulated amortization of mining properties',
    statement: 'assets',
  },
  {
    code: '1626',
    name: 'Deferred exploration and development charges',
    statement: 'assets',
  },
  {
    code: '1627',
    name: 'Accumulated amortization of deferred exploration and development charges',
    statement: 'assets',
  },
  { code: '1628', name: 'Quarries', statement: 'assets' },
  {
    code: '1629',
    name: 'Accumulated amortization of quarries',
    statement: 'assets',
  },
  { code: '1630', name: 'Gravel pits', statement: 'assets' },
  {
    code: '1631',
    name: 'Accumulated amortization of gravel pits',
    statement: 'assets',
  },
  { code: '1632', name: 'Timber limits', statement: 'assets' },
  {
    code: '1633',
    name: 'Accumulated amortization of timber limits',
    statement: 'assets',
  },
  { code: '1680', name: 'Buildings', statement: 'assets' },
  {
    code: '1681',
    name: 'Accumulated amortization of buildings',
    statement: 'assets',
  },
  {
    code: '1682',
    name: 'Manufacturing and processing plant',
    statement: 'assets',
  },
  {
    code: '1683',
    name: 'Accumulated amortization of manufacturing and processing plant',
    statement: 'assets',
  },
  { code: '1684', name: 'Buildings under construction', statement: 'assets' },
  {
    code: '1740',
    name: 'Machinery, equipment, furniture, and fixtures',
    statement: 'assets',
  },
  {
    code: '1741',
    name: 'Accumulated amortization of machinery, equipment, furniture, and fixtures',
    statement: 'assets',
  },
  { code: '1742', name: 'Motor vehicles', statement: 'assets' },
  {
    code: '1743',
    name: 'Accumulated amortization of motor vehicles',
    statement: 'assets',
  },
  { code: '1744', name: 'Tools and dies', statement: 'assets' },
  {
    code: '1745',
    name: 'Accumulated amortization of tools and dies',
    statement: 'assets',
  },
  {
    code: '1746',
    name: 'Construction and excavating equipment',
    statement: 'assets',
  },
  {
    code: '1747',
    name: 'Accumulated amortization of construction and excavating equipment',
    statement: 'assets',
  },
  { code: '1748', name: 'Forestry and logging equipment', statement: 'assets' },
  {
    code: '1749',
    name: 'Accumulated amortization of forestry and logging equipment',
    statement: 'assets',
  },
  { code: '1750', name: 'Fishing gear and nets', statement: 'assets' },
  {
    code: '1751',
    name: 'Accumulated amortization of fishing gear and nets',
    statement: 'assets',
  },
  { code: '1752', name: 'Mining equipment', statement: 'assets' },
  {
    code: '1753',
    name: 'Accumulated amortization of mining equipment',
    statement: 'assets',
  },
  { code: '1754', name: 'Oil and gas systems', statement: 'assets' },
  {
    code: '1755',
    name: 'Accumulated amortization of oil and gas systems',
    statement: 'assets',
  },
  {
    code: '1756',
    name: 'Production equipment for resource industries',
    statement: 'assets',
  },
  {
    code: '1757',
    name: 'Accumulated amortization of production equipment for resource industries',
    statement: 'assets',
  },
  {
    code: '1758',
    name: 'Production equipment for other than resource industries',
    statement: 'assets',
  },
  {
    code: '1759',
    name: 'Accumulated amortization of production equipment for other than resource industries',
    statement: 'assets',
  },
  { code: '1760', name: 'Exploration equipment', statement: 'assets' },
  {
    code: '1761',
    name: 'Accumulated amortization of exploration equipment',
    statement: 'assets',
  },
  { code: '1762', name: 'Shipping equipment', statement: 'assets' },
  {
    code: '1763',
    name: 'Accumulated amortization of shipping equipment',
    statement: 'assets',
  },
  { code: '1764', name: 'Ships and boats', statement: 'assets' },
  {
    code: '1765',
    name: 'Accumulated amortization of ships and boats',
    statement: 'assets',
  },
  { code: '1766', name: 'Aircraft', statement: 'assets' },
  {
    code: '1767',
    name: 'Accumulated amortization of aircraft',
    statement: 'assets',
  },
  { code: '1768', name: 'Signs', statement: 'assets' },
  {
    code: '1769',
    name: 'Accumulated amortization of signs',
    statement: 'assets',
  },
  { code: '1770', name: 'Small tools', statement: 'assets' },
  {
    code: '1771',
    name: 'Accumulated amortization of small tools',
    statement: 'assets',
  },
  {
    code: '1772',
    name: 'Radio and communication equipment',
    statement: 'assets',
  },
  {
    code: '1773',
    name: 'Accumulated amortization of radio and communication equipment',
    statement: 'assets',
  },
  { code: '1774', name: 'Computer equipment/software', statement: 'assets' },
  {
    code: '1775',
    name: 'Accumulated amortization of computer equipment/software',
    statement: 'assets',
  },
  { code: '1776', name: 'Musical instruments', statement: 'assets' },
  {
    code: '1777',
    name: 'Accumulated amortization of musical instruments',
    statement: 'assets',
  },
  { code: '1778', name: 'Satellites', statement: 'assets' },
  {
    code: '1779',
    name: 'Accumulated amortization of satellites',
    statement: 'assets',
  },
  { code: '1780', name: 'Earth stations', statement: 'assets' },
  {
    code: '1781',
    name: 'Accumulated amortization of earth stations',
    statement: 'assets',
  },
  {
    code: '1782',
    name: 'Machinery and equipment under construction',
    statement: 'assets',
  },
  { code: '1783', name: 'Transportation equipment', statement: 'assets' },
  {
    code: '1784',
    name: 'Accumulated amortization of transportation equipment',
    statement: 'assets',
  },
  { code: '1785', name: 'Other machinery and equipment', statement: 'assets' },
  {
    code: '1786',
    name: 'Accumulated amortization of other machinery and equipment',
    statement: 'assets',
  },
  { code: '1900', name: 'Other tangible capital assets', statement: 'assets' },
  {
    code: '1901',
    name: 'Accumulated amortization of other tangible capital assets',
    statement: 'assets',
  },
  { code: '1902', name: 'Logging roads', statement: 'assets' },
  {
    code: '1903',
    name: 'Accumulated amortization of logging roads',
    statement: 'assets',
  },
  { code: '1904', name: 'Asphalt and parking areas', statement: 'assets' },
  {
    code: '1905',
    name: 'Accumulated amortization of asphalt and parking areas',
    statement: 'assets',
  },
  { code: '1906', name: 'Wharves', statement: 'assets' },
  {
    code: '1907',
    name: 'Accumulated amortization of wharves',
    statement: 'assets',
  },
  { code: '1908', name: 'Fences', statement: 'assets' },
  {
    code: '1909',
    name: 'Accumulated amortization of fences',
    statement: 'assets',
  },
  { code: '1910', name: 'Capital leases - Buildings', statement: 'assets' },
  {
    code: '1911',
    name: 'Accumulated amortization of capital leases - Buildings',
    statement: 'assets',
  },
  { code: '1912', name: 'Capital leases - Equipment', statement: 'assets' },
  {
    code: '1913',
    name: 'Accumulated amortization of capital leases - Equipment',
    statement: 'assets',
  },
  { code: '1914', name: 'Capital leases - Vehicles', statement: 'assets' },
  {
    code: '1915',
    name: 'Accumulated amortization of capital leases - Vehicles',
    statement: 'assets',
  },
  { code: '1916', name: 'Capital leases - Others', statement: 'assets' },
  {
    code: '1917',
    name: 'Accumulated amortization of capital leases - Others',
    statement: 'assets',
  },
  { code: '1918', name: 'Leasehold improvements', statement: 'assets' },
  {
    code: '1919',
    name: 'Accumulated amortization of leasehold improvements',
    statement: 'assets',
  },
  {
    code: '1920',
    name: 'Other capital assets under construction',
    statement: 'assets',
  },
  { code: '1921', name: 'Campsites', statement: 'assets' },
  {
    code: '1922',
    name: 'Accumulated amortization of campsites',
    statement: 'assets',
  },
  { code: '2008', name: 'Total tangible capital assets', statement: 'assets' },
  {
    code: '2009',
    name: 'Total accumulated amortization of tangible capital assets',
    statement: 'assets',
  },
  { code: '2010', name: 'Intangible assets', statement: 'assets' },
  {
    code: '2011',
    name: 'Accumulated amortization of intangible assets',
    statement: 'assets',
  },
  { code: '2012', name: 'Goodwill', statement: 'assets' },
  {
    code: '2013',
    name: 'Accumulated amortization of goodwill',
    statement: 'assets',
  },
  { code: '2014', name: 'Quota', statement: 'assets' },
  {
    code: '2015',
    name: 'Accumulated amortization of quota',
    statement: 'assets',
  },
  { code: '2016', name: 'Licences', statement: 'assets' },
  {
    code: '2017',
    name: 'Accumulated amortization of licences',
    statement: 'assets',
  },
  {
    code: '2018',
    name: 'Incorporation costs (corporations only)',
    statement: 'assets',
  },
  {
    code: '2019',
    name: 'Accumulated amortization of incorporation costs (corporations only)',
    statement: 'assets',
  },
  { code: '2020', name: 'Trademarks/patents', statement: 'assets' },
  {
    code: '2021',
    name: 'Accumulated amortization of trademarks/patents',
    statement: 'assets',
  },
  { code: '2022', name: 'Customer lists', statement: 'assets' },
  {
    code: '2023',
    name: 'Accumulated amortization of customer lists',
    statement: 'assets',
  },
  { code: '2024', name: 'Rights', statement: 'assets' },
  {
    code: '2025',
    name: 'Accumulated amortization of rights',
    statement: 'assets',
  },
  { code: '2026', name: 'Research and development', statement: 'assets' },
  {
    code: '2027',
    name: 'Accumulated amortization of research and development',
    statement: 'assets',
  },
  { code: '2070', name: 'Resource rights', statement: 'assets' },
  {
    code: '2071',
    name: 'Accumulated amortization of resource rights',
    statement: 'assets',
  },
  { code: '2072', name: 'Timber rights', statement: 'assets' },
  {
    code: '2073',
    name: 'Accumulated amortization of timber rights',
    statement: 'assets',
  },
  { code: '2074', name: 'Mining rights', statement: 'assets' },
  {
    code: '2075',
    name: 'Accumulated amortization of mining rights',
    statement: 'assets',
  },
  { code: '2076', name: 'Oil and gas rights', statement: 'assets' },
  {
    code: '2077',
    name: 'Accumulated amortization of oil and gas rights',
    statement: 'assets',
  },
  {
    code: '2178',
    name: 'Total intangible capital assets',
    statement: 'assets',
  },
  {
    code: '2179',
    name: 'Total accumulated amortization of intangible capital assets',
    statement: 'assets',
  },
  {
    code: '2180',
    name: 'Due from shareholder(s)/director(s)',
    statement: 'assets',
  },
  {
    code: '2181',
    name: 'Due from individual shareholder(s)',
    statement: 'assets',
  },
  {
    code: '2182',
    name: 'Due from corporate shareholder(s)',
    statement: 'assets',
  },
  { code: '2183', name: 'Due from director(s)', statement: 'assets' },
  { code: '2190', name: 'Due from members', statement: 'assets' },
  {
    code: '2200',
    name: 'Investment in joint venture(s)/partnership(s)',
    statement: 'assets',
  },
  {
    code: '2210',
    name: 'Due from member(s)/general partner(s)',
    statement: 'assets',
  },
  { code: '2211', name: 'Due from limited partners', statement: 'assets' },
  {
    code: '2212',
    name: 'Due from members that are partnerships',
    statement: 'assets',
  },
  { code: '2213', name: 'Due from general partners', statement: 'assets' },
  {
    code: '2214',
    name: 'Due from specified members who are not limited partners',
    statement: 'assets',
  },
  {
    code: '2220',
    name: 'Due from joint venture(s)/partnership(s)',
    statement: 'assets',
  },
  {
    code: '2240',
    name: 'Due from/investment in related parties',
    statement: 'assets',
  },
  {
    code: '2241',
    name: 'Due from/investment in Canadian related parties',
    statement: 'assets',
  },
  {
    code: '2242',
    name: 'Shares in Canadian related corporations',
    statement: 'assets',
  },
  {
    code: '2243',
    name: 'Loans/advances to Canadian related corporations',
    statement: 'assets',
  },
  {
    code: '2244',
    name: 'Investment in Canadian related corporations at cost',
    statement: 'assets',
  },
  {
    code: '2245',
    name: 'Investment in Canadian related corporations at equity',
    statement: 'assets',
  },
  {
    code: '2246',
    name: 'Due from/investment in foreign related parties',
    statement: 'assets',
  },
  {
    code: '2247',
    name: 'Shares in foreign related corporations',
    statement: 'assets',
  },
  {
    code: '2248',
    name: 'Loans/advances to foreign related corporations',
    statement: 'assets',
  },
  {
    code: '2249',
    name: 'Investment in foreign related corporations at cost',
    statement: 'assets',
  },
  {
    code: '2250',
    name: 'Investment in foreign related corporations at equity',
    statement: 'assets',
  },
  { code: '2280', name: 'Investment in co-tenancy', statement: 'assets' },
  { code: '2300', name: 'Long-term investments', statement: 'assets' },
  { code: '2301', name: 'Foreign shares', statement: 'assets' },
  {
    code: '2302',
    name: 'Other types of foreign investments',
    statement: 'assets',
  },
  { code: '2303', name: 'Canadian shares', statement: 'assets' },
  { code: '2304', name: 'Government of Canada debt', statement: 'assets' },
  {
    code: '2305',
    name: 'Canadian, provincial, and municipal government debt',
    statement: 'assets',
  },
  {
    code: '2306',
    name: 'Canadian corporate bonds and debentures',
    statement: 'assets',
  },
  { code: '2307', name: 'Debt securities', statement: 'assets' },
  { code: '2308', name: 'Equity securities', statement: 'assets' },
  {
    code: '2309',
    name: 'Securities purchased under resale agreements',
    statement: 'assets',
  },
  { code: '2310', name: 'Central credit union shares', statement: 'assets' },
  {
    code: '2311',
    name: 'Other Canadian long-term investments',
    statement: 'assets',
  },
  { code: '2360', name: 'Long-term loans', statement: 'assets' },
  { code: '2361', name: 'Mortgages', statement: 'assets' },
  { code: '2362', name: 'Personal and credit card loans', statement: 'assets' },
  { code: '2363', name: 'Business and government loans', statement: 'assets' },
  { code: '2364', name: 'Line of credit', statement: 'assets' },
  { code: '2420', name: 'Other long-term assets', statement: 'assets' },
  {
    code: '2421',
    name: 'Future (deferred) income taxes (corporations only)',
    statement: 'assets',
  },
  { code: '2422', name: 'Deferred pension charges', statement: 'assets' },
  {
    code: '2423',
    name: 'Deferred unrealized exchange losses',
    statement: 'assets',
  },
  { code: '2424', name: 'Other deferred items/charges', statement: 'assets' },
  {
    code: '2425',
    name: 'Accumulated amortization of deferred charges',
    statement: 'assets',
  },
  { code: '2426', name: 'Reserve fund', statement: 'assets' },
  {
    code: '2427',
    name: 'Cash surrender value of life insurance',
    statement: 'assets',
  },
  { code: '2589', name: 'Total long-term assets', statement: 'assets' },
  { code: '2590', name: 'Assets held in trust', statement: 'assets' },
  { code: '2599', name: 'Total assets', statement: 'assets' },
  { code: '2600', name: 'Bank overdraft', statement: 'liabilities' },
  {
    code: '2620',
    name: 'Amounts payable and accrued liabilities',
    statement: 'liabilities',
  },
  { code: '2621', name: 'Trade payables', statement: 'liabilities' },
  {
    code: '2622',
    name: 'Trade payables to related parties',
    statement: 'liabilities',
  },
  { code: '2623', name: 'Holdbacks payable', statement: 'liabilities' },
  { code: '2624', name: 'Wages payable', statement: 'liabilities' },
  { code: '2625', name: 'Management fees payable', statement: 'liabilities' },
  { code: '2626', name: 'Bonuses payable', statement: 'liabilities' },
  {
    code: '2627',
    name: 'Employee deductions payable',
    statement: 'liabilities',
  },
  { code: '2628', name: 'Withholding taxes payable', statement: 'liabilities' },
  { code: '2629', name: 'Interest payable', statement: 'liabilities' },
  {
    code: '2630',
    name: 'Amounts payable to members of NPOs',
    statement: 'liabilities',
  },
  { code: '2680', name: 'Taxes payable', statement: 'liabilities' },
  { code: '2700', name: 'Short-term debt', statement: 'liabilities' },
  { code: '2701', name: 'Loans from Canadian banks', statement: 'liabilities' },
  {
    code: '2702',
    name: 'Liability for securities sold short',
    statement: 'liabilities',
  },
  {
    code: '2703',
    name: 'Liability for securities sold under repurchase agreements',
    statement: 'liabilities',
  },
  {
    code: '2704',
    name: 'Gold and silver certificates',
    statement: 'liabilities',
  },
  {
    code: '2705',
    name: 'Cheques and other items in transit',
    statement: 'liabilities',
  },
  { code: '2706', name: 'Lien notes', statement: 'liabilities' },
  {
    code: '2707',
    name: 'Credit card loans Include purchases made on your credit card for the purpose of earning business income.',
    statement: 'liabilities',
  },
  { code: '2770', name: 'Deferred income', statement: 'liabilities' },
  {
    code: '2780',
    name: 'Due to shareholder(s)/director(s)',
    statement: 'liabilities',
  },
  {
    code: '2781',
    name: 'Due to individual shareholder(s)',
    statement: 'liabilities',
  },
  {
    code: '2782',
    name: 'Due to corporate shareholder(s)',
    statement: 'liabilities',
  },
  { code: '2783', name: 'Due to director(s)', statement: 'liabilities' },
  {
    code: '2790',
    name: 'Due to member(s)/general partner(s)',
    statement: 'liabilities',
  },
  { code: '2791', name: 'Due to limited partners', statement: 'liabilities' },
  {
    code: '2792',
    name: 'Due to members that are partnerships',
    statement: 'liabilities',
  },
  { code: '2793', name: 'Due to general partners', statement: 'liabilities' },
  {
    code: '2794',
    name: 'Due to specified members who are not limited partners',
    statement: 'liabilities',
  },
  {
    code: '2840',
    name: 'Due to joint venture(s)/partnership(s)',
    statement: 'liabilities',
  },
  { code: '2860', name: 'Due to related parties', statement: 'liabilities' },
  {
    code: '2861',
    name: 'Demand notes due to related parties',
    statement: 'liabilities',
  },
  {
    code: '2862',
    name: 'Interest payable to related parties',
    statement: 'liabilities',
  },
  {
    code: '2863',
    name: 'Advances due to related parties',
    statement: 'liabilities',
  },
  { code: '2940', name: "Bankers' acceptances", statement: 'liabilities' },
  { code: '2960', name: 'Other current liabilities', statement: 'liabilities' },
  { code: '2961', name: 'Deposits received', statement: 'liabilities' },
  { code: '2962', name: 'Dividends payable', statement: 'liabilities' },
  {
    code: '2963',
    name: 'Future (deferred) income taxes (corporations only)',
    statement: 'liabilities',
  },
  {
    code: '2964',
    name: 'Reserves for guarantees, warranties, or indemnities',
    statement: 'liabilities',
  },
  {
    code: '2965',
    name: 'General provisions/reserves',
    statement: 'liabilities',
  },
  { code: '2966', name: 'Crew shares', statement: 'liabilities' },
  { code: '3139', name: 'Total current liabilities', statement: 'liabilities' },
  { code: '3140', name: 'Long-term debt', statement: 'liabilities' },
  { code: '3141', name: 'Mortgages', statement: 'liabilities' },
  {
    code: '3142',
    name: 'Farm Credit Corporation loan',
    statement: 'liabilities',
  },
  { code: '3143', name: 'Chartered bank loan', statement: 'liabilities' },
  {
    code: '3144',
    name: 'Credit Union/Caisse Populaire loan',
    statement: 'liabilities',
  },
  {
    code: '3145',
    name: 'Provincial or territorial government loan',
    statement: 'liabilities',
  },
  { code: '3146', name: 'Supply company loan', statement: 'liabilities' },
  { code: '3147', name: 'Private loan', statement: 'liabilities' },
  {
    code: '3148',
    name: 'Central, league, and federation loans',
    statement: 'liabilities',
  },
  { code: '3149', name: 'Line of credit', statement: 'liabilities' },
  {
    code: '3150',
    name: 'Liability for securities sold short',
    statement: 'liabilities',
  },
  {
    code: '3151',
    name: 'Liability for securities sold under repurchase agreements',
    statement: 'liabilities',
  },
  { code: '3152', name: 'Lien notes', statement: 'liabilities' },
  {
    code: '3200',
    name: 'Deposit liabilities of financial institutions',
    statement: 'liabilities',
  },
  { code: '3210', name: 'Bonds and debentures', statement: 'liabilities' },
  { code: '3220', name: 'Deferred income', statement: 'liabilities' },
  {
    code: '3240',
    name: 'Future (deferred) income taxes',
    statement: 'liabilities',
  },
  {
    code: '3260',
    name: 'Due to shareholder(s)/director(s)',
    statement: 'liabilities',
  },
  {
    code: '3261',
    name: 'Due to individual shareholder(s)',
    statement: 'liabilities',
  },
  {
    code: '3262',
    name: 'Due to corporate shareholder(s)',
    statement: 'liabilities',
  },
  { code: '3263', name: 'Due to director(s)', statement: 'liabilities' },
  { code: '3270', name: 'Due to members', statement: 'liabilities' },
  {
    code: '3280',
    name: 'Due to joint venture(s)/partnership(s)',
    statement: 'liabilities',
  },
  {
    code: '3291',
    name: 'Due to member(s)/general partner(s)',
    statement: 'liabilities',
  },
  { code: '3292', name: 'Due to limited partners', statement: 'liabilities' },
  {
    code: '3293',
    name: 'Due to members that are partnerships',
    statement: 'liabilities',
  },
  { code: '3294', name: 'Due to general partners', statement: 'liabilities' },
  {
    code: '3295',
    name: 'Due to specified members who are not limited partners',
    statement: 'liabilities',
  },
  { code: '3300', name: 'Due to related parties', statement: 'liabilities' },
  {
    code: '3301',
    name: 'Amounts owing to related Canadian parties',
    statement: 'liabilities',
  },
  {
    code: '3302',
    name: 'Amounts owing to related foreign parties',
    statement: 'liabilities',
  },
  {
    code: '3320',
    name: 'Other long-term liabilities',
    statement: 'liabilities',
  },
  {
    code: '3321',
    name: 'Long-term obligations/commitments/capital leases',
    statement: 'liabilities',
  },
  {
    code: '3322',
    name: 'Reserves for guarantees, warranties, or indemnities',
    statement: 'liabilities',
  },
  {
    code: '3323',
    name: 'Provision for site restoration',
    statement: 'liabilities',
  },
  {
    code: '3324',
    name: 'Contributions to qualifying environmental trust',
    statement: 'liabilities',
  },
  {
    code: '3325',
    name: 'General provisions/reserves',
    statement: 'liabilities',
  },
  {
    code: '3326',
    name: 'Preference shares restated (corporations only)',
    statement: 'liabilities',
  },
  {
    code: '3327',
    name: 'Member allocations (corporations only)',
    statement: 'liabilities',
  },
  {
    code: '3328',
    name: 'Deferred revenue from incomplete contracts',
    statement: 'liabilities',
  },
  {
    code: '3450',
    name: 'Total long-term liabilities',
    statement: 'liabilities',
  },
  { code: '3460', name: 'Subordinated debt', statement: 'liabilities' },
  { code: '3470', name: 'Amounts held in trust', statement: 'liabilities' },
  { code: '3499', name: 'Total liabilities', statement: 'liabilities' },
  { code: '3500', name: 'Common shares', statement: 'equity' },
  { code: '3520', name: 'Preferred shares', statement: 'equity' },
  { code: '3540', name: 'Contributed and other surplus', statement: 'equity' },
  { code: '3541', name: 'Contributed surplus', statement: 'equity' },
  { code: '3542', name: 'Appraisal surplus', statement: 'equity' },
  { code: '3543', name: 'General reserve', statement: 'equity' },
  { code: '3570', name: 'Head office account', statement: 'equity' },
  {
    code: '3580',
    name: 'Accumulated other comprehensive income',
    statement: 'equity',
  },
  { code: '3600', name: 'Retained earnings/deficit', statement: 'equity' },
  { code: '3620', name: 'Total shareholder equity', statement: 'equity' },
  {
    code: '3640',
    name: 'Total liabilities and shareholder equity',
    statement: 'equity',
  },
  { code: '3545', name: 'Net income/loss', statement: 'equity' },
  { code: '3546', name: 'Prior period adjustments', statement: 'equity' },
  { code: '3547', name: 'Currency adjustments', statement: 'equity' },
  { code: '3548', name: 'Unusual revenue items', statement: 'equity' },
  { code: '3550', name: 'Total net income/loss', statement: 'equity' },
  {
    code: '3551',
    name: "General partners' capital beginning balance",
    statement: 'equity',
  },
  {
    code: '3552',
    name: "General partners' net income (loss)",
    statement: 'equity',
  },
  { code: '3553', name: "General partners' drawings", statement: 'equity' },
  {
    code: '3554',
    name: "General partners' contributions during the fiscal period",
    statement: 'equity',
  },
  {
    code: '3560',
    name: "General partners' capital ending balance",
    statement: 'equity',
  },
  {
    code: '3561',
    name: "Limited partners' capital beginning balance",
    statement: 'equity',
  },
  {
    code: '3562',
    name: "Limited partners' net income (loss)",
    statement: 'equity',
  },
  { code: '3563', name: "Limited partners' drawings", statement: 'equity' },
  {
    code: '3564',
    name: "Limited partners' contribution during the fiscal period",
    statement: 'equity',
  },
  {
    code: '3571',
    name: "Limited partners' capital ending balance",
    statement: 'equity',
  },
  { code: '3575', name: "Total partners' capital", statement: 'equity' },
  {
    code: '3585',
    name: "Total liabilities and partners' capital",
    statement: 'equity',
  },
  {
    code: '3660',
    name: 'Retained earnings/deficit - Start',
    statement: 'equity',
  },
  { code: '3680', name: 'Net income/loss', statement: 'equity' },
  { code: '3700', name: 'Dividends declared', statement: 'equity' },
  { code: '3701', name: 'Cash dividends', statement: 'equity' },
  { code: '3702', name: 'Patronage dividends', statement: 'equity' },
  { code: '3720', name: 'Prior period adjustments', statement: 'equity' },
  {
    code: '3740',
    name: 'Other items affecting retained earnings',
    statement: 'equity',
  },
  { code: '3741', name: 'Share redemptions', statement: 'equity' },
  {
    code: '3742',
    name: 'Special reserves (corporations and co-ops only)',
    statement: 'equity',
  },
  { code: '3743', name: 'Currency adjustments', statement: 'equity' },
  { code: '3744', name: 'Unusual revenue items', statement: 'equity' },
  { code: '3745', name: 'Interfund transfer', statement: 'equity' },
  {
    code: '3849',
    name: 'Retained earnings/deficit - End',
    statement: 'equity',
  },
  { code: '7000', name: 'Revaluation surplus', statement: 'revenue' },
  { code: '7002', name: 'Defined benefit gains/losses', statement: 'revenue' },
  {
    code: '7004',
    name: 'Foreign operation translation gains/losses',
    statement: 'revenue',
  },
  {
    code: '7006',
    name: 'Equity instruments gains/losses',
    statement: 'revenue',
  },
  {
    code: '7008',
    name: 'Cash flow hedge effective portion gains/losses',
    statement: 'revenue',
  },
  {
    code: '7010',
    name: 'Income tax relating to components of other comprehensive income',
    statement: 'revenue',
  },
  {
    code: '7020',
    name: 'Miscellaneous other comprehensive income',
    statement: 'revenue',
  },
  {
    code: '8000',
    name: 'Trade sales of goods and services',
    statement: 'revenue',
  },
  {
    code: '8020',
    name: 'Sales of goods and services to related parties',
    statement: 'revenue',
  },
  { code: '8030', name: 'Interdivisional sales', statement: 'revenue' },
  {
    code: '8040',
    name: 'Sales from resource properties',
    statement: 'revenue',
  },
  { code: '8053', name: 'Other production revenue', statement: 'revenue' },
  {
    code: '8089',
    name: 'Total sales of goods and services',
    statement: 'revenue',
  },
  { code: '8090', name: 'Investment revenue', statement: 'revenue' },
  { code: '8091', name: 'Interest from foreign sources', statement: 'revenue' },
  {
    code: '8092',
    name: 'Interest from Canadian bonds and debentures',
    statement: 'revenue',
  },
  {
    code: '8093',
    name: 'Interest from Canadian mortgage loans',
    statement: 'revenue',
  },
  {
    code: '8094',
    name: 'Interest from other Canadian sources',
    statement: 'revenue',
  },
  {
    code: '8096',
    name: 'Dividends from Canadian sources',
    statement: 'revenue',
  },
  {
    code: '8097',
    name: 'Dividends from foreign sources',
    statement: 'revenue',
  },
  {
    code: '8100',
    name: 'Interest income (financial institutions)',
    statement: 'revenue',
  },
  { code: '8103', name: "Deposits with banks' interest", statement: 'revenue' },
  { code: '8120', name: 'Commission revenue', statement: 'revenue' },
  {
    code: '8121',
    name: 'Commission income on real estate transactions',
    statement: 'revenue',
  },
  { code: '8140', name: 'Rental revenue', statement: 'revenue' },
  { code: '8141', name: 'Real estate rental revenue', statement: 'revenue' },
  { code: '8142', name: 'Film rental revenue', statement: 'revenue' },
  { code: '8150', name: 'Vehicle leasing', statement: 'revenue' },
  { code: '8160', name: 'Fishing revenue', statement: 'revenue' },
  { code: '8162', name: 'Other marine products', statement: 'revenue' },
  {
    code: '8165',
    name: 'Compensation for loss of fishing income or property',
    statement: 'revenue',
  },
  {
    code: '8210',
    name: 'Realized gains/losses on disposal of assets',
    statement: 'revenue',
  },
  {
    code: '8211',
    name: 'Realized gains/losses on sale of investments',
    statement: 'revenue',
  },
  {
    code: '8212',
    name: 'Realized gains/losses on sale of resource properties',
    statement: 'revenue',
  },
  { code: '8220', name: 'NPO amounts received', statement: 'revenue' },
  { code: '8221', name: 'Membership fees', statement: 'revenue' },
  { code: '8222', name: 'Assessments', statement: 'revenue' },
  { code: '8223', name: 'Gifts', statement: 'revenue' },
  {
    code: '8224',
    name: 'Gross sales and revenues from organizational activities',
    statement: 'revenue',
  },
  { code: '8230', name: 'Other revenue', statement: 'revenue' },
  { code: '8231', name: 'Foreign exchange gains/losses', statement: 'revenue' },
  {
    code: '8232',
    name: 'Income/loss of subsidiaries/affiliates',
    statement: 'revenue',
  },
  {
    code: '8233',
    name: 'Income/loss of other divisions',
    statement: 'revenue',
  },
  { code: '8234', name: 'Income/loss of joint ventures', statement: 'revenue' },
  { code: '8235', name: 'Income/loss of partnerships', statement: 'revenue' },
  {
    code: '8236',
    name: 'Realization of deferred revenues',
    statement: 'revenue',
  },
  { code: '8238', name: 'Alberta royalty tax credits', statement: 'revenue' },
  {
    code: '8239',
    name: 'Management and administration fees',
    statement: 'revenue',
  },
  { code: '8240', name: 'Telecommunications revenue', statement: 'revenue' },
  { code: '8241', name: 'Consulting fees', statement: 'revenue' },
  { code: '8243', name: 'Sale of by-products', statement: 'revenue' },
  { code: '8244', name: 'Deposit services', statement: 'revenue' },
  { code: '8245', name: 'Credit services', statement: 'revenue' },
  { code: '8246', name: 'Card services', statement: 'revenue' },
  { code: '8247', name: 'Patronage dividends', statement: 'revenue' },
  { code: '8248', name: 'Insurance recoveries', statement: 'revenue' },
  { code: '8249', name: 'Expense recoveries', statement: 'revenue' },
  { code: '8250', name: 'Bad debt recoveries', statement: 'revenue' },
  { code: '8299', name: 'Total revenue', statement: 'revenue' },
  { code: '8300', name: 'Opening inventory', statement: 'expenses' },
  {
    code: '8301',
    name: 'Opening inventory - Finished goods',
    statement: 'expenses',
  },
  {
    code: '8302',
    name: 'Opening inventory - Raw materials',
    statement: 'expenses',
  },
  {
    code: '8303',
    name: 'Opening inventory - Goods in process',
    statement: 'expenses',
  },
  { code: '8320', name: 'Purchases/cost of materials', statement: 'expenses' },
  { code: '8340', name: 'Direct wages', statement: 'expenses' },
  { code: '8350', name: 'Benefits on direct wages', statement: 'expenses' },
  { code: '8360', name: 'Trades and sub-contracts', statement: 'expenses' },
  {
    code: '8370',
    name: 'Production costs other than resource',
    statement: 'expenses',
  },
  { code: '8400', name: 'Resource production costs', statement: 'expenses' },
  { code: '8401', name: 'Pipeline operations', statement: 'expenses' },
  { code: '8402', name: 'Drilling', statement: 'expenses' },
  { code: '8403', name: 'Site restoration costs', statement: 'expenses' },
  { code: '8404', name: 'Gross overriding royalty', statement: 'expenses' },
  { code: '8405', name: 'Freehold royalties', statement: 'expenses' },
  {
    code: '8406',
    name: 'Other producing properties rental',
    statement: 'expenses',
  },
  { code: '8407', name: 'Prospect/geological', statement: 'expenses' },
  {
    code: '8408',
    name: 'Well operating, fuel and equipment',
    statement: 'expenses',
  },
  {
    code: '8409',
    name: 'Well abandonment and dry holes',
    statement: 'expenses',
  },
  { code: '8410', name: 'Other lease rentals', statement: 'expenses' },
  { code: '8411', name: 'Exploration expenses', statement: 'expenses' },
  { code: '8412', name: 'Development expenses', statement: 'expenses' },
  { code: '8435', name: 'Crown charges', statement: 'expenses' },
  { code: '8436', name: 'Crown royalties', statement: 'expenses' },
  { code: '8437', name: 'Crown lease rentals', statement: 'expenses' },
  { code: '8438', name: 'Freehold mineral tax', statement: 'expenses' },
  { code: '8439', name: 'Mining taxes', statement: 'expenses' },
  { code: '8440', name: 'Oil sand leases', statement: 'expenses' },
  {
    code: '8441',
    name: 'Saskatchewan resource surcharge',
    statement: 'expenses',
  },
  { code: '8450', name: 'Other direct costs', statement: 'expenses' },
  { code: '8451', name: 'Equipment hire and operation', statement: 'expenses' },
  { code: '8452', name: 'Log yard', statement: 'expenses' },
  { code: '8453', name: 'Forestry costs', statement: 'expenses' },
  { code: '8454', name: 'Logging road costs', statement: 'expenses' },
  { code: '8455', name: 'Stumpage costs', statement: 'expenses' },
  { code: '8456', name: 'Royalty costs', statement: 'expenses' },
  { code: '8457', name: 'Freight-in and duty', statement: 'expenses' },
  { code: '8458', name: 'Inventory write-down', statement: 'expenses' },
  {
    code: '8459',
    name: 'Direct cost amortization of tangible assets',
    statement: 'expenses',
  },
  {
    code: '8460',
    name: 'Direct cost amortization of natural resource assets',
    statement: 'expenses',
  },
  {
    code: '8461',
    name: 'Overhead expenses allocated to cost of sales',
    statement: 'expenses',
  },
  { code: '8500', name: 'Closing inventory', statement: 'expenses' },
  {
    code: '8501',
    name: 'Closing inventory - Finished goods',
    statement: 'expenses',
  },
  {
    code: '8502',
    name: 'Closing inventory - Raw materials',
    statement: 'expenses',
  },
  {
    code: '8503',
    name: 'Closing inventory - Goods in process',
    statement: 'expenses',
  },
  { code: '8518', name: 'Cost of sales', statement: 'expenses' },
  { code: '8519', name: 'Gross profit/loss', statement: 'expenses' },
  { code: '8520', name: 'Advertising and promotion', statement: 'expenses' },
  { code: '8521', name: 'Advertising', statement: 'expenses' },
  { code: '8522', name: 'Donations', statement: 'expenses' },
  { code: '8523', name: 'Meals and entertainment', statement: 'expenses' },
  { code: '8524', name: 'Promotion', statement: 'expenses' },
  {
    code: '8570',
    name: 'Amortization of intangible assets',
    statement: 'expenses',
  },
  { code: '8571', name: 'Goodwill impairment loss', statement: 'expenses' },
  { code: '8590', name: 'Bad debt expense', statement: 'expenses' },
  { code: '8610', name: 'Loan losses', statement: 'expenses' },
  { code: '8611', name: 'Provision for loan losses', statement: 'expenses' },
  { code: '8620', name: 'Employee benefits', statement: 'expenses' },
  { code: '8621', name: 'Group insurance benefits', statement: 'expenses' },
  {
    code: '8622',
    name: "Employer's portion of employee benefits",
    statement: 'expenses',
  },
  {
    code: '8623',
    name: 'Contributions to deferred income plans',
    statement: 'expenses',
  },
  {
    code: '8650',
    name: 'Amortization of natural resource assets',
    statement: 'expenses',
  },
  {
    code: '8670',
    name: 'Amortization of tangible assets',
    statement: 'expenses',
  },
  { code: '8690', name: 'Insurance', statement: 'expenses' },
  { code: '8691', name: 'Life insurance on executives', statement: 'expenses' },
  { code: '8710', name: 'Interest and bank charges', statement: 'expenses' },
  { code: '8711', name: 'Interest on short-term debt', statement: 'expenses' },
  {
    code: '8712',
    name: 'Interest on bonds and debentures',
    statement: 'expenses',
  },
  { code: '8713', name: 'Interest on mortgages', statement: 'expenses' },
  { code: '8714', name: 'Interest on long-term debt', statement: 'expenses' },
  { code: '8715', name: 'Bank charges', statement: 'expenses' },
  { code: '8716', name: 'Credit card charges', statement: 'expenses' },
  { code: '8717', name: 'Collection and credit costs', statement: 'expenses' },
  {
    code: '8740',
    name: 'Interest paid (financial institutions)',
    statement: 'expenses',
  },
  { code: '8741', name: 'Interest paid on deposits', statement: 'expenses' },
  {
    code: '8742',
    name: 'Interest paid on bonds and debentures',
    statement: 'expenses',
  },
  {
    code: '8760',
    name: 'Business taxes, licences, and memberships',
    statement: 'expenses',
  },
  { code: '8761', name: 'Memberships', statement: 'expenses' },
  { code: '8762', name: 'Business taxes', statement: 'expenses' },
  { code: '8763', name: 'Franchise fees', statement: 'expenses' },
  { code: '8764', name: 'Government fees', statement: 'expenses' },
  {
    code: '8790',
    name: 'Nova Scotia tax on large corporations',
    statement: 'expenses',
  },
  { code: '8810', name: 'Office expenses', statement: 'expenses' },
  {
    code: '8811',
    name: 'Office stationery and supplies',
    statement: 'expenses',
  },
  { code: '8812', name: 'Office utilities', statement: 'expenses' },
  { code: '8813', name: 'Data processing', statement: 'expenses' },
  { code: '8860', name: 'Professional fees', statement: 'expenses' },
  { code: '8861', name: 'Legal fees', statement: 'expenses' },
  { code: '8862', name: 'Accounting fees', statement: 'expenses' },
  { code: '8863', name: 'Consulting fees', statement: 'expenses' },
  { code: '8864', name: 'Architect fees', statement: 'expenses' },
  { code: '8865', name: 'Appraisal fees', statement: 'expenses' },
  { code: '8866', name: 'Laboratory fees', statement: 'expenses' },
  { code: '8867', name: 'Medical fees', statement: 'expenses' },
  { code: '8868', name: 'Veterinary fees', statement: 'expenses' },
  { code: '8869', name: 'Brokerage fees', statement: 'expenses' },
  { code: '8870', name: 'Transfer fees', statement: 'expenses' },
  {
    code: '8871',
    name: 'Management and administration fees',
    statement: 'expenses',
  },
  { code: '8872', name: 'Refining and assay', statement: 'expenses' },
  {
    code: '8873',
    name: 'Registrar and transfer agent fees',
    statement: 'expenses',
  },
  { code: '8874', name: 'Restructuring costs', statement: 'expenses' },
  { code: '8875', name: 'Security commission fees', statement: 'expenses' },
  { code: '8876', name: 'Training expense', statement: 'expenses' },
  { code: '8877', name: 'Studio and recording', statement: 'expenses' },
  { code: '8910', name: 'Rental', statement: 'expenses' },
  { code: '8911', name: 'Real estate rental', statement: 'expenses' },
  { code: '8912', name: 'Occupancy costs', statement: 'expenses' },
  { code: '8913', name: 'Condominium fees', statement: 'expenses' },
  { code: '8914', name: 'Equipment rental', statement: 'expenses' },
  { code: '8915', name: 'Motor vehicle rentals', statement: 'expenses' },
  { code: '8916', name: 'Moorage (boat)', statement: 'expenses' },
  { code: '8917', name: 'Storage', statement: 'expenses' },
  { code: '8918', name: 'Quota rental', statement: 'expenses' },
  { code: '8960', name: 'Repairs and maintenance', statement: 'expenses' },
  {
    code: '8961',
    name: 'Repairs and maintenance - Buildings',
    statement: 'expenses',
  },
  {
    code: '8962',
    name: 'Repairs and maintenance - Vehicles',
    statement: 'expenses',
  },
  {
    code: '8963',
    name: 'Repairs and maintenance - Boats',
    statement: 'expenses',
  },
  {
    code: '8964',
    name: 'Repairs and maintenance - Machinery and equipment',
    statement: 'expenses',
  },
  {
    code: '9010',
    name: 'Other repairs and maintenance',
    statement: 'expenses',
  },
  { code: '9011', name: 'Machine shop expense', statement: 'expenses' },
  { code: '9012', name: 'Road costs', statement: 'expenses' },
  { code: '9013', name: 'Security', statement: 'expenses' },
  { code: '9014', name: 'Garbage removal', statement: 'expenses' },
  { code: '9060', name: 'Salaries and wages', statement: 'expenses' },
  { code: '9061', name: 'Commissions', statement: 'expenses' },
  { code: '9062', name: 'Crew share', statement: 'expenses' },
  { code: '9063', name: 'Bonuses', statement: 'expenses' },
  { code: '9064', name: 'Directors fees', statement: 'expenses' },
  { code: '9065', name: 'Management salaries', statement: 'expenses' },
  { code: '9066', name: 'Employee salaries', statement: 'expenses' },
  { code: '9110', name: 'Sub-contracts', statement: 'expenses' },
  { code: '9130', name: 'Supplies', statement: 'expenses' },
  { code: '9131', name: 'Small tools', statement: 'expenses' },
  { code: '9132', name: 'Shop expense', statement: 'expenses' },
  { code: '9133', name: 'Uniforms', statement: 'expenses' },
  { code: '9134', name: 'Laundry', statement: 'expenses' },
  { code: '9135', name: 'Food and catering', statement: 'expenses' },
  { code: '9136', name: 'Fishing gear', statement: 'expenses' },
  { code: '9137', name: 'Nets and traps', statement: 'expenses' },
  { code: '9138', name: 'Salt, bait, and ice', statement: 'expenses' },
  { code: '9139', name: 'Camp supplies', statement: 'expenses' },
  { code: '9150', name: 'Computer-related expenses', statement: 'expenses' },
  { code: '9151', name: 'Upgrade', statement: 'expenses' },
  { code: '9152', name: 'Internet', statement: 'expenses' },
  { code: '9180', name: 'Property taxes', statement: 'expenses' },
  { code: '9200', name: 'Travel expenses', statement: 'expenses' },
  { code: '9201', name: 'Meetings and conventions', statement: 'expenses' },
  { code: '9220', name: 'Utilities', statement: 'expenses' },
  { code: '9221', name: 'Electricity', statement: 'expenses' },
  { code: '9222', name: 'Water', statement: 'expenses' },
  { code: '9223', name: 'Heat', statement: 'expenses' },
  { code: '9224', name: 'Fuel costs', statement: 'expenses' },
  {
    code: '9225',
    name: 'Telephone and telecommunications',
    statement: 'expenses',
  },
  { code: '9270', name: 'Other expenses', statement: 'expenses' },
  { code: '9271', name: 'Cash over/short', statement: 'expenses' },
  {
    code: '9272',
    name: 'Reimbursement of parent company expense (corporations only)',
    statement: 'expenses',
  },
  { code: '9273', name: 'Selling expenses', statement: 'expenses' },
  {
    code: '9274',
    name: 'Shipping and warehouse expense',
    statement: 'expenses',
  },
  {
    code: '9275',
    name: 'Delivery, freight and express',
    statement: 'expenses',
  },
  { code: '9276', name: 'Warranty expenses', statement: 'expenses' },
  { code: '9277', name: 'Royalty expenses - Resident', statement: 'expenses' },
  {
    code: '9278',
    name: 'Royalty expenses - Non-resident',
    statement: 'expenses',
  },
  { code: '9279', name: 'Dumping charges', statement: 'expenses' },
  { code: '9280', name: 'Land fill fees', statement: 'expenses' },
  { code: '9281', name: 'Vehicle expenses', statement: 'expenses' },
  { code: '9282', name: 'Research and development', statement: 'expenses' },
  { code: '9283', name: 'Withholding taxes', statement: 'expenses' },
  {
    code: '9284',
    name: 'General and administrative expenses',
    statement: 'expenses',
  },
  { code: '9285', name: 'Interdivisional expenses', statement: 'expenses' },
  { code: '9286', name: 'Interfund transfer', statement: 'expenses' },
  { code: '9367', name: 'Total operating expenses', statement: 'expenses' },
  { code: '9368', name: 'Total expenses', statement: 'expenses' },
  { code: '9369', name: 'Net non-farming income', statement: 'expenses' },
  { code: '0001', name: 'Operating name', statement: 'assets' },
  { code: '0002', name: 'Description of the operation', statement: 'assets' },
  { code: '0003', name: 'Sequence number', statement: 'assets' },
  { code: '9370', name: 'Grains and oilseeds', statement: 'farming' },
  { code: '9371', name: 'Wheat', statement: 'farming' },
  { code: '9372', name: 'Oats', statement: 'farming' },
  { code: '9373', name: 'Barley', statement: 'farming' },
  { code: '9374', name: 'Mixed grains', statement: 'farming' },
  { code: '9375', name: 'Corn', statement: 'farming' },
  { code: '9376', name: 'Canola', statement: 'farming' },
  { code: '9377', name: 'Flaxseed', statement: 'farming' },
  { code: '9378', name: 'Soya beans', statement: 'farming' },
  { code: '9379', name: 'Wheat Board payments', statement: 'farming' },
  { code: '9420', name: 'Other crop revenues', statement: 'farming' },
  { code: '9421', name: 'Fruit', statement: 'farming' },
  { code: '9422', name: 'Potatoes', statement: 'farming' },
  { code: '9423', name: 'Vegetables', statement: 'farming' },
  { code: '9424', name: 'Tobacco', statement: 'farming' },
  {
    code: '9425',
    name: 'Greenhouse and nursery products',
    statement: 'farming',
  },
  { code: '9426', name: 'Forage crops', statement: 'farming' },
  {
    code: '9470',
    name: 'Livestock and animal products revenue',
    statement: 'farming',
  },
  { code: '9471', name: 'Cattle', statement: 'farming' },
  { code: '9472', name: 'Swine', statement: 'farming' },
  { code: '9473', name: 'Poultry', statement: 'farming' },
  { code: '9474', name: 'Sheep and lambs', statement: 'farming' },
  { code: '9475', name: 'Pregnant mare urine (PMU)', statement: 'farming' },
  {
    code: '9476',
    name: 'Milk and cream (excluding dairy subsidies)',
    statement: 'farming',
  },
  { code: '9477', name: 'Eggs for consumption', statement: 'farming' },
  { code: '9478', name: 'Hatching eggs', statement: 'farming' },
  {
    code: '9479',
    name: 'Aquaculture (hatching and raising)',
    statement: 'farming',
  },
  { code: '9480', name: 'Horses (breeding and meat)', statement: 'farming' },
  { code: '9520', name: 'Other commodities', statement: 'farming' },
  { code: '9521', name: 'Maple products', statement: 'farming' },
  { code: '9522', name: 'Artificial insemination', statement: 'farming' },
  { code: '9523', name: 'Semen production', statement: 'farming' },
  { code: '9524', name: 'Embryo production', statement: 'farming' },
  { code: '9540', name: 'Program payment revenues', statement: 'farming' },
  { code: '9541', name: 'Dairy subsidies', statement: 'farming' },
  { code: '9542', name: 'Crop insurance', statement: 'farming' },
  {
    code: '9544',
    name: 'Disaster Assistance Program payments',
    statement: 'farming',
  },
  {
    code: '9545',
    name: 'AgriStability and AgriInvest benefit',
    statement: 'farming',
  },
  {
    code: '9546',
    name: 'Production insurance premium benefit',
    statement: 'farming',
  },
  { code: '9570', name: 'Rebates', statement: 'farming' },
  { code: '9571', name: 'Rebates - Fuel', statement: 'farming' },
  { code: '9572', name: 'Rebates - Interest', statement: 'farming' },
  { code: '9573', name: 'Rebates - Property taxes', statement: 'farming' },
  { code: '9600', name: 'Other farm revenues/losses', statement: 'farming' },
  { code: '9601', name: 'Custom or contract work', statement: 'farming' },
  { code: '9602', name: 'Wood sales', statement: 'farming' },
  { code: '9603', name: 'Horse racing', statement: 'farming' },
  { code: '9604', name: 'Insurance proceeds', statement: 'farming' },
  { code: '9605', name: 'Patronage dividends', statement: 'farming' },
  { code: '9606', name: 'Rental income', statement: 'farming' },
  { code: '9607', name: 'Interest income', statement: 'farming' },
  { code: '9608', name: 'Dividend income', statement: 'farming' },
  {
    code: '9609',
    name: 'Gains/losses on disposal of assets',
    statement: 'farming',
  },
  { code: '9610', name: 'Gravel', statement: 'farming' },
  { code: '9611', name: 'Trucking', statement: 'farming' },
  {
    code: '9612',
    name: 'Resale of commodities purchased',
    statement: 'farming',
  },
  {
    code: '9613',
    name: 'Leases (such as gas, oil, well, and surface)',
    statement: 'farming',
  },
  { code: '9614', name: 'Machine rentals', statement: 'farming' },
  {
    code: '9615',
    name: 'Farming partnership income/loss',
    statement: 'farming',
  },
  {
    code: '9616',
    name: 'Farming joint venture income/loss',
    statement: 'farming',
  },
  { code: '9617', name: 'Custom feeding', statement: 'farming' },
  { code: '9650', name: 'Non-farming income', statement: 'farming' },
  { code: '9659', name: 'Total farm revenue', statement: 'farming' },
  { code: '9660', name: 'Crop expenses', statement: 'farming' },
  {
    code: '9661',
    name: 'Containers, twine, and baling wire',
    statement: 'farming',
  },
  { code: '9662', name: 'Fertilizers and lime', statement: 'farming' },
  { code: '9663', name: 'Pesticides', statement: 'farming' },
  { code: '9664', name: 'Seeds and plants', statement: 'farming' },
  { code: '9710', name: 'Livestock expenses', statement: 'farming' },
  {
    code: '9711',
    name: 'Feed, supplements, straw, and bedding',
    statement: 'farming',
  },
  { code: '9712', name: 'Livestock purchases', statement: 'farming' },
  {
    code: '9713',
    name: 'Veterinary fees, medicine, and breeding fees',
    statement: 'farming',
  },
  { code: '9714', name: 'Minerals and salts', statement: 'farming' },
  { code: '9760', name: 'Machinery expenses', statement: 'farming' },
  { code: '9761', name: 'Machinery insurance', statement: 'farming' },
  { code: '9762', name: 'Machinery licences', statement: 'farming' },
  { code: '9763', name: 'Machinery repairs', statement: 'farming' },
  { code: '9764', name: 'Machinery fuel', statement: 'farming' },
  { code: '9765', name: 'Machinery lease', statement: 'farming' },
  { code: '9790', name: 'General farm expenses', statement: 'farming' },
  {
    code: '9791',
    name: 'Amortization of tangible assets',
    statement: 'farming',
  },
  {
    code: '9792',
    name: 'Advertising, marketing costs, and promotion',
    statement: 'farming',
  },
  { code: '9793', name: 'Bad debt', statement: 'farming' },
  {
    code: '9794',
    name: 'Benefits related to employee salaries',
    statement: 'farming',
  },
  {
    code: '9795',
    name: 'Building repairs and maintenance',
    statement: 'farming',
  },
  {
    code: '9796',
    name: 'Clearing, levelling, and draining land',
    statement: 'farming',
  },
  {
    code: '9797',
    name: 'Crop insurance, Revenue Protection Program, and stabilization premiums',
    statement: 'farming',
  },
  { code: '9798', name: 'Custom or contract work', statement: 'farming' },
  { code: '9799', name: 'Electricity', statement: 'farming' },
  { code: '9800', name: 'Fence repairs and maintenance', statement: 'farming' },
  { code: '9801', name: 'Freight and trucking', statement: 'farming' },
  { code: '9802', name: 'Heating fuel and curing fuel', statement: 'farming' },
  {
    code: '9803',
    name: 'Insurance program overpayment recapture',
    statement: 'farming',
  },
  { code: '9804', name: 'Other insurance premiums', statement: 'farming' },
  { code: '9805', name: 'Interest and bank charges', statement: 'farming' },
  { code: '9806', name: 'Marketing board fees', statement: 'farming' },
  { code: '9807', name: 'Memberships/subscription fees', statement: 'farming' },
  { code: '9808', name: 'Office expenses', statement: 'farming' },
  { code: '9809', name: 'Professional fees', statement: 'farming' },
  { code: '9810', name: 'Property taxes', statement: 'farming' },
  { code: '9811', name: 'Rent - Land and buildings', statement: 'farming' },
  { code: '9813', name: 'Other rental expenses', statement: 'farming' },
  {
    code: '9815',
    name: 'Salaries and wages other than for spouse or dependants',
    statement: 'farming',
  },
  {
    code: '9816',
    name: 'Salaries and wages paid to dependants',
    statement: 'farming',
  },
  { code: '9817', name: 'Selling costs', statement: 'farming' },
  { code: '9818', name: 'Supplies', statement: 'farming' },
  { code: '9819', name: 'Motor vehicle expenses', statement: 'farming' },
  { code: '9820', name: 'Small tools', statement: 'farming' },
  { code: '9821', name: 'Soil testing', statement: 'farming' },
  { code: '9822', name: 'Storage/drying', statement: 'farming' },
  { code: '9823', name: 'Licences/permits', statement: 'farming' },
  { code: '9824', name: 'Telephone', statement: 'farming' },
  { code: '9825', name: 'Quota rental (tobacco, dairy)', statement: 'farming' },
  { code: '9826', name: 'Gravel', statement: 'farming' },
  {
    code: '9827',
    name: 'Purchases of commodities resold',
    statement: 'farming',
  },
  {
    code: '9828',
    name: 'Salaries and wages paid to spouse',
    statement: 'farming',
  },
  {
    code: '9829',
    name: 'Motor vehicle interest and leasing costs',
    statement: 'farming',
  },
  { code: '9830', name: 'Prepared feed', statement: 'farming' },
  { code: '9831', name: 'Custom feed', statement: 'farming' },
  { code: '9833', name: 'Amortization of milk quota', statement: 'farming' },
  { code: '9834', name: 'Travel expenses', statement: 'farming' },
  { code: '9835', name: 'Capital/business taxes', statement: 'farming' },
  { code: '9836', name: 'Commissions and levies', statement: 'farming' },
  { code: '9850', name: 'Non-farming expenses', statement: 'farming' },
  { code: '9870', name: 'Net inventory adjustment', statement: 'farming' },
  { code: '9898', name: 'Total farm expenses', statement: 'farming' },
  { code: '9899', name: 'Net farm income', statement: 'farming' },
  {
    code: '9970',
    name: 'Net income/loss before taxes and extraordinary items',
    statement: 'extraordinary_and_taxes',
  },
  {
    code: '9975',
    name: 'Extraordinary item(s)',
    statement: 'extraordinary_and_taxes',
  },
  {
    code: '9976',
    name: 'Legal settlements',
    statement: 'extraordinary_and_taxes',
  },
  {
    code: '9980',
    name: 'Unrealized gains/losses',
    statement: 'extraordinary_and_taxes',
  },
  { code: '9985', name: 'Unusual items', statement: 'extraordinary_and_taxes' },
  {
    code: '9990',
    name: 'Current income taxes',
    statement: 'extraordinary_and_taxes',
  },
  {
    code: '9995',
    name: 'Future (deferred) income tax provision',
    statement: 'extraordinary_and_taxes',
  },
  {
    code: '9998',
    name: 'Total-other comprehensive income',
    statement: 'extraordinary_and_taxes',
  },
  {
    code: '9999',
    name: 'Net income/loss after taxes and extraordinary items',
    statement: 'extraordinary_and_taxes',
  },
]
