import { describe, expect, it } from 'vitest'
import {
  generateTheme,
  getThemeDeclarations,
  serializeTheme,
} from '../index.js'

describe('theme serialization', () => {
  it('serializes prefixed declarations, aliases, and replaceable scopes', () => {
    const theme = generateTheme({
      neutral: '#777',
      accent: '#06c',
      contrast: 50,
      prefix: 'brand',
    })
    const declarations = getThemeDeclarations(theme, 'light')
    expect(declarations[0]?.name).toContain('--brand-')
    expect(declarations.map((declaration) => declaration.path)).toEqual(
      [...declarations.map((declaration) => declaration.path)].sort(),
    )
    expect(theme.light.tokens.shadow[0]).toBe('none')
    expect(theme.light.tokens.shadow[1]).toContain('inset 0 1px 0')
    expect(theme.light.tokens.shadow[1]).toContain('0 0 0 1px')
    expect(theme.light.tokens.shadow[1]).toContain('0 1px 2px')
    expect(theme.light.tokens.shadow[4]).toContain('0 12px 32px')
    expect(theme.light.tokens.glow.accent).toContain('0 8px 24px')
    const css = serializeTheme(theme, {
      lightSelector: '.light',
      darkSelector: '.dark',
    })
    expect(serializeTheme(theme)).toContain(
      '/* Generated by @bazza-ui/colors */\n[data-bui-theme="light"] {',
    )
    expect(serializeTheme(theme)).toContain('[data-bui-theme="dark"] {')
    expect(serializeTheme(theme)).not.toMatch(/202\d[-/]/)
    expect(css).toContain('.light {')
    expect(css).toContain('--color-surface-0: var(--brand-surface-0);')
    expect(css).not.toMatch(
      /--(?:background|primary|secondary|muted|accent|foreground)(?=:)/,
    )
    expect(css).toBe(
      serializeTheme(theme, { lightSelector: '.light', darkSelector: '.dark' }),
    )
    expect(theme.light.tokens.shadow[1]).toContain('rgb(255 255 255 / 0.065)')
    expect(theme.light.tokens.shadow[1]).toContain('rgb(0 0 0 / 0.0875)')
  })
})
