import type { ButtonVariant } from '../components/button/types.js'
import type { GeneratedTheme, ThemeMode } from './types.js'

export type ThemeDeclaration = Readonly<{
  path: string
  name: string
  value: string
}>
export type ThemeSerializerOptions = Readonly<{
  lightSelector?: string
  darkSelector?: string
}>
const variants: readonly ButtonVariant[] = [
  'primary-neutral',
  'primary-accent',
  'destructive',
  'outline',
  'secondary',
  'ghost',
  'link',
]
const states = ['rest', 'hover', 'active', 'focus'] as const
const flatten = (value: unknown, path = ''): [string, string][] => {
  if (typeof value === 'string') return [[path, value]]
  return Object.entries(value as Record<string, unknown>).flatMap(
    ([key, child]) => flatten(child, path ? `${path}.${key}` : key),
  )
}
export function getThemeDeclarations(
  theme: GeneratedTheme,
  mode: ThemeMode,
): readonly ThemeDeclaration[] {
  const core = flatten(theme[mode].tokens)
  const button = variants.flatMap((variant) =>
    states.flatMap((state) => {
      const token = theme[mode].components.button[variant][state]
      const suffix = state === 'rest' ? '' : `.${state}`
      return [
        [`button.${variant}.background${suffix}`, token.background],
        [`button.${variant}.foreground${suffix}`, token.foreground],
        [`button.${variant}.border${suffix}`, token.border],
        [`button.${variant}.shadow${suffix}`, token.boxShadow],
      ] as [string, string][]
    }),
  )
  return [...core, ...button]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([path, value]) => ({
      path,
      name: `--${theme.prefix}-${path.replaceAll('.', '-')}`,
      value,
    }))
}
export function serializeTheme(
  theme: GeneratedTheme,
  options?: ThemeSerializerOptions,
): string {
  const scopes = (['light', 'dark'] as const).map((mode) => {
    const selector =
      mode === 'light'
        ? (options?.lightSelector ?? `[data-bui-theme="light"]`)
        : (options?.darkSelector ?? `[data-bui-theme="dark"]`)
    const declarations = getThemeDeclarations(theme, mode)
    const raw = declarations.flatMap(({ path, name, value }) => [
      `  ${name}: ${value};`,
      ...(path.startsWith('button.')
        ? []
        : [`  --color-${path.replaceAll('.', '-')}: var(${name});`]),
    ])
    const blocks = variants.map((variant) => {
      const local = states.flatMap((state) => {
        const suffix = state === 'rest' ? '' : `-${state}`
        return [
          `  --button-background${suffix}: var(--${theme.prefix}-button-${variant}-background${suffix});`,
          `  --button-foreground${suffix}: var(--${theme.prefix}-button-${variant}-foreground${suffix});`,
          `  --button-border${suffix}: var(--${theme.prefix}-button-${variant}-border${suffix});`,
          `  --button-shadow${suffix}: var(--${theme.prefix}-button-${variant}-shadow${suffix});`,
        ]
      })
      return `${selector} [data-slot="button"][data-variant="${variant}"] {\n${local.join('\n')}\n}`
    })
    return `${selector} {\n${raw.join('\n')}\n}\n\n${blocks.join('\n')}`
  })
  return `/* Generated by @bazza-ui/colors */\n${scopes.join('\n\n')}\n`
}
