import type { GeneratedTheme, ThemeMode } from './types.js'

export type ThemeDeclaration = Readonly<{
  path: string
  name: string
  value: string
}>
export type ThemeSerializerOptions = Readonly<{
  lightSelector?: string
  darkSelector?: string
}>
const flatten = (value: unknown, path = ''): [string, string][] => {
  if (typeof value === 'string') return [[path, value]]
  return Object.entries(value as Record<string, unknown>).flatMap(
    ([key, child]) => flatten(child, path ? `${path}.${key}` : key),
  )
}
export function getThemeDeclarations(
  theme: GeneratedTheme,
  mode: ThemeMode,
): readonly ThemeDeclaration[] {
  return flatten(theme[mode].tokens)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([path, value]) => ({
      path,
      name: `--${theme.prefix}-${path.replaceAll('.', '-')}`,
      value,
    }))
}
export function serializeTheme(
  theme: GeneratedTheme,
  options?: ThemeSerializerOptions,
): string {
  const scopes = (
    [
      ['light', options?.lightSelector ?? `[data-bui-theme="light"]`],
      ['dark', options?.darkSelector ?? `[data-bui-theme="dark"]`],
    ] as const
  ).map(([mode, selector]) => {
    const declarations = getThemeDeclarations(theme, mode)
    const lines = declarations.flatMap(({ path, name, value }) => [
      `  ${name}: ${value};`,
      `  --color-${path.replaceAll('.', '-')}: var(${name});`,
    ])
    return `${selector} {\n${lines.join('\n')}\n}`
  })
  return `/* Generated by @bazza-ui/colors */\n${scopes.join('\n\n')}\n`
}
