export const labelData = [
  { id: 'bug', name: 'Bug', color: 'red', keywords: ['issue', 'fix'] },
  {
    id: 'enhancement',
    name: 'Enhancement',
    color: 'green',
    keywords: ['feature', 'improvement'],
  },
  { id: 'task', name: 'Task', color: 'blue', keywords: ['todo', 'work'] },
  {
    id: 'urgent',
    name: 'Urgent',
    color: 'pink',
    keywords: ['critical', 'asap'],
  },
  {
    id: 'low-priority',
    name: 'Low Priority',
    color: 'lime',
    keywords: ['minor', 'backlog'],
  },
  {
    id: 'frontend',
    name: 'Frontend',
    color: 'orange',
    keywords: ['ui', 'client'],
  },
  {
    id: 'backend',
    name: 'Backend',
    color: 'teal',
    keywords: ['server', 'api'],
  },
  {
    id: 'database',
    name: 'Database',
    color: 'violet',
    keywords: ['db', 'sql', 'storage'],
  },
  {
    id: 'api',
    name: 'API',
    color: 'red',
    keywords: ['endpoint', 'rest', 'graphql'],
  },
  {
    id: 'ai-model',
    name: 'AI Model',
    color: 'cyan',
    keywords: ['ml', 'machine learning'],
  },
  {
    id: 'data-pipeline',
    name: 'Data Pipeline',
    color: 'amber',
    keywords: ['etl', 'processing'],
  },
  {
    id: 'inference',
    name: 'Inference',
    color: 'emerald',
    keywords: ['prediction', 'model'],
  },
  {
    id: 'ai-integration',
    name: 'AI Integration',
    color: 'purple',
    keywords: ['llm', 'openai'],
  },
  {
    id: 'ethics',
    name: 'Ethics',
    color: 'fuchsia',
    keywords: ['compliance', 'responsible'],
  },
  {
    id: 'refactor',
    name: 'Refactor',
    color: 'lime',
    keywords: ['cleanup', 'restructure'],
  },
  {
    id: 'performance',
    name: 'Performance',
    color: 'red',
    keywords: ['speed', 'optimization'],
  },
  {
    id: 'security',
    name: 'Security',
    color: 'sky',
    keywords: ['vulnerability', 'auth'],
  },
  {
    id: 'testing',
    name: 'Testing',
    color: 'yellow',
    keywords: ['test', 'qa', 'unit'],
  },
  {
    id: 'documentation',
    name: 'Documentation',
    color: 'rose',
    keywords: ['docs', 'readme'],
  },
  {
    id: 'in-progress',
    name: 'In Progress',
    color: 'green',
    keywords: ['wip', 'active'],
  },
  {
    id: 'blocked',
    name: 'Blocked',
    color: 'indigo',
    keywords: ['stuck', 'waiting'],
  },
  {
    id: 'needs-review',
    name: 'Needs Review',
    color: 'orange',
    keywords: ['pr', 'review'],
  },
  {
    id: 'done',
    name: 'Done',
    color: 'teal',
    keywords: ['complete', 'finished'],
  },
  { id: 'ui', name: 'UI', color: 'red', keywords: ['interface', 'visual'] },
  { id: 'ux', name: 'UX', color: 'sky', keywords: ['experience', 'usability'] },
  {
    id: 'accessibility',
    name: 'Accessibility',
    color: 'red',
    keywords: ['a11y', 'wcag'],
  },
  {
    id: 'deployment',
    name: 'Deployment',
    color: 'emerald',
    keywords: ['release', 'ship'],
  },
  {
    id: 'infrastructure',
    name: 'Infrastructure',
    color: 'purple',
    keywords: ['devops', 'cloud'],
  },
  {
    id: 'monitoring',
    name: 'Monitoring',
    color: 'pink',
    keywords: ['logs', 'alerts'],
  },
  {
    id: 'real-time',
    name: 'Real-Time',
    color: 'lime',
    keywords: ['websocket', 'live'],
  },
]

export const LABEL_STYLES_BG = {
  red: 'bg-red-500',
  orange: 'bg-orange-500',
  amber: 'bg-amber-500',
  yellow: 'bg-yellow-500',
  lime: 'bg-lime-500',
  green: 'bg-green-500',
  emerald: 'bg-emerald-500',
  teal: 'bg-teal-500',
  cyan: 'bg-cyan-500',
  sky: 'bg-sky-500',
  blue: 'bg-blue-500',
  indigo: 'bg-indigo-500',
  violet: 'bg-violet-500',
  purple: 'bg-purple-500',
  fuchsia: 'bg-fuchsia-500',
  pink: 'bg-pink-500',
  rose: 'bg-rose-500',
  neutral: 'bg-neutral-500',
} as const

export type TW_COLOR = keyof typeof LABEL_STYLES_BG
